### PR TITLE
For #13116: fix serialization issues.

### PR DESCRIPTION
**Pull request by ksallee**
Convert AnyDictionary to dict to avoid JSON serialization issues when calling sg.find

Note: we use `.metadata` all over the place, and this fixes the problem at hand, but I'm worried about this being an issue whenever the data returned from our classes etc is used for querying SG.

Not sure what the best approach is to wrap everything.

### CODE REVIEW

**Review by gplsteph — CHANGES_REQUESTED** [review]
Not approving because the very first thing which should have been done is writing tests to reproduce the problem, and then fixing it.
It looks as well that the fix should be with `X.metadata` so it is a regular dict, or JSON serialisable instead of patching things everywhere?

**Comment by ksallee** [comment]
> Not approving because the very first thing which should have been done is writing tests to reproduce the problem, and then fixing it. It looks as well that the fix should be with `X.metadata` so it is a regular dict, or JSON serialisable instead of patching things everywhere?


hey @gplsteph, there are tests in place, lines modified are already covered by tests normally (as reported by codecov).
We use `X.metadata` all over the place, and the problem is that even if you do something like `metadata = dict(X.metadata)` that does not work, because nested dictionaries will be AnyDictionaries too.

I tried to figure out a way of changing this (serialization, type of metadata) without disrupting the code too much, but I did not find any solution. Like I said in the description, "Not sure what the best approach is to wrap everything."

If you have any ideas I'm all ears.

**Comment by ksallee** [comment]
@gplsteph I updated mockgun in the tests, so now without my modifications some tests fail, and with it they pass. Not sure how to centralize the serialization of metadata, if you have an idea please let me know.

**Comment by gplsteph** [comment]
Should the fix actually be in otio? Where are defined those `AnyDictionary`?

**Pull request closed without merging**
